/**
 * @aigentflow/agents - Agent Framework
 *
 * Core agent infrastructure for Aigentflow orchestration.
 * Provides base classes, registry, and context management for agents.
 *
 * @packageDocumentation
 */

// Types and schemas
export {
  // Enums
  AgentTypeEnum,
  ContextTypeEnum,
  ArtifactTypeEnum,
  // Schemas
  AgentTypeSchema,
  ContextTypeSchema,
  ArtifactTypeSchema,
  TaskAnalysisSchema,
  AuthContextSchema,
  AgentCapabilitySchema,
  ContextRequirementSchema,
  AgentMetadataSchema,
  ContextItemSchema,
  AgentConstraintsSchema,
  AgentContextSchema,
  RoutingHintsSchema,
  ArtifactSchema,
  ExecutionMetricsSchema,
  AgentErrorSchema,
  AgentOutputSchema,
  AgentExecutionOptionsSchema,
  AgentRequestSchema,
  AgentStatusSchema,
  // Types
  type AgentType,
  type ContextType,
  type ArtifactType,
  type TaskAnalysis,
  type AuthContext,
  type AgentCapability,
  type ContextRequirement,
  type AgentMetadata,
  type ContextItem,
  type AgentConstraints,
  type AgentContext,
  type RoutingHints,
  type Artifact,
  type ExecutionMetrics,
  type AgentError,
  type AgentOutput,
  type AgentExecutionOptions,
  type AgentRequest,
  type AgentStatus,
  // Constants
  DEFAULT_CONSTRAINTS,
  // Errors
  SecurityViolationError,
  AgentValidationError,
  AgentExecutionError,
} from './types.js';

// Base agent
export { BaseAgent } from './base-agent.js';

// Registry
export {
  AgentRegistry,
  getRegistry,
  RegisterAgent,
  type RegistryStats,
} from './registry.js';

// Context manager
export {
  ContextManager,
  createMemoryContextSource,
  DEFAULT_CONTEXT_BUDGET,
  ContextFetchParamsSchema,
  type ContextSource,
  type ContextFetchParams,
  type ContextBudget,
  type CuratedContext,
} from './context-manager.js';

// Orchestrator schemas
export {
  TaskClassificationSchema,
  RoutingDecisionSchema,
  ReasoningResultSchema,
  OrchestratorPhaseSchema,
  OrchestratorStateSchema,
  ConflictSchema,
  KeyOutputSchema,
  SynthesisResultSchema,
  FailureAnalysisSchema,
  DecisionContextSchema,
  OrchestratorOutputSchema,
  UserInputSchema,
  OrchestrationConfigSchema,
  DEFAULT_ORCHESTRATION_CONFIG,
  type TaskClassification,
  type RoutingDecision,
  type ReasoningResult,
  type OrchestratorPhase,
  type OrchestratorState,
  type Conflict,
  type KeyOutput,
  type SynthesisResult,
  type FailureAnalysis,
  type DecisionContext,
  type OrchestratorOutput,
  type OrchestrationConfig,
} from './schemas/orchestrator-output.js';

// Orchestration components
export {
  DecisionEngine,
  type DecisionResult,
} from './orchestration/decision-engine.js';

export {
  Router,
  type RoutingResult,
} from './orchestration/router.js';

export {
  Synthesizer,
  type MergedArtifact,
} from './orchestration/synthesizer.js';

// Orchestrator agent
export { OrchestratorAgent } from './agents/orchestrator.js';

// Project Manager schemas
export {
  TaskTypeSchema,
  ComplexitySchema,
  PrioritySchema,
  RiskSeveritySchema,
  RiskSchema,
  TaskSchema,
  FeatureSchema,
  EpicSchema,
  BlockerSchema,
  WorkBreakdownSummarySchema,
  PMRoutingHintsSchema,
  ProjectManagerOutputSchema,
  WorkBreakdownValidationSchema,
  DEFAULT_COMPLEXITY_DISTRIBUTION,
  DEFAULT_TASK_TYPE_DISTRIBUTION,
  COMPLEXITY_EFFORT_HOURS,
  type TaskType,
  type Complexity,
  type Priority,
  type RiskSeverity,
  type Risk,
  type Task,
  type Feature,
  type Epic,
  type Blocker,
  type WorkBreakdownSummary,
  type PMRoutingHints,
  type ProjectManagerOutput,
  type WorkBreakdownValidation,
} from './schemas/project-manager-output.js';

// Planning utilities
export {
  generateId,
  createEpic,
  createFeature,
  createTask,
  flattenTasks,
  flattenFeatures,
  getTaskById,
  getFeatureById,
  getEpicById,
  calculateSummary,
  validateWorkBreakdown,
  getTasksByType,
  getTasksByComplexity,
  getComplianceTasks,
  getRootTasks,
  countTasksByAgent,
  mergeWorkBreakdowns,
  DependencyGraph,
  type CycleInfo,
} from './planning/index.js';

// Project Manager agent
export { ProjectManagerAgent } from './agents/project-manager.js';

// Architect schemas
export {
  TechnologySchema,
  FrontendStackSchema,
  BackendStackSchema,
  DatabaseStackSchema,
  InfrastructureStackSchema,
  TestingStackSchema,
  TechStackSchema,
  ADRStatusSchema,
  ADRAlternativeSchema,
  ADRConsequencesSchema,
  ADRSchema,
  ComponentTypeSchema,
  InterfaceTypeSchema,
  ComponentInterfaceSchema,
  ComponentSchema,
  HTTPMethodSchema,
  BodySchemaDefinition,
  APIEndpointSchema,
  DataFieldSchema,
  RelationshipTypeSchema,
  RelationshipSchema,
  DataModelSchema,
  DirectoryStructureSchema,
  NamingConventionsSchema,
  FormattingConventionsSchema,
  PatternSchema,
  AntiPatternSchema,
  CodingConventionsSchema,
  ArchitectRoutingHintsSchema,
  ArchitectOutputSchema,
  createADR,
  generateADRId,
  type Technology,
  type FrontendStack,
  type BackendStack,
  type DatabaseStack,
  type InfrastructureStack,
  type TestingStack,
  type TechStack,
  type ADRStatus,
  type ADRAlternative,
  type ADRConsequences,
  type ADR,
  type ComponentType,
  type InterfaceType,
  type ComponentInterface,
  type Component,
  type HTTPMethod,
  type BodySchema,
  type APIEndpoint,
  type DataField,
  type RelationshipType,
  type Relationship,
  type DataModel,
  type DirectoryStructure,
  type NamingConventions,
  type FormattingConventions,
  type Pattern,
  type AntiPattern,
  type CodingConventions,
  type ArchitectRoutingHints,
  type ArchitectOutput,
} from './schemas/architect-output.js';

// Architecture utilities
export {
  ADRManager,
  renderDirectoryStructure,
  renderCodingConventions,
  type ADRCreateOptions,
} from './architecture/index.js';

// Architect agent
export { ArchitectAgent } from './agents/architect.js';

// Analyst schemas
export {
  SourceTypeSchema,
  CredibilitySchema,
  SourceSchema,
  PopularitySchema,
  MaintenanceSchema,
  LearningCurveSchema,
  CommunitySizeSchema,
  ComparisonOptionSchema,
  ComparisonSchema,
  BestPracticeSchema,
  FindingSchema,
  AlternativeSchema,
  ImplementationSchema,
  RecommendationSchema,
  ReportTypeSchema,
  AnalystRoutingHintsSchema,
  AnalystOutputSchema,
  createSource,
  createRecommendation,
  createComparisonOption,
  createFinding,
  calculateAverageConfidence,
  countSourcesByCredibility,
  type SourceType,
  type Credibility,
  type Source,
  type Popularity,
  type Maintenance,
  type LearningCurve,
  type CommunitySize,
  type ComparisonOption,
  type Comparison,
  type BestPractice,
  type Finding,
  type Alternative,
  type Implementation,
  type Recommendation,
  type ReportType,
  type AnalystRoutingHints,
  type AnalystOutput,
} from './schemas/analyst-output.js';

// Analyst agent
export { AnalystAgent } from './agents/analyst.js';

// Analyst style research schemas (design workflow)
export {
  // Schemas
  ColorMentionSchema,
  FontMentionSchema,
  InspirationUrlSchema,
  PlatformHintSchema,
  PromptStyleAnalysisSchema,
  CompetitorAnalysisSchema,
  DomainResearchSchema,
  TechRecommendationSchema,
  StyleConstraintsSchema,
  StyleResearchOutputSchema,
  // Types
  type ColorMention,
  type FontMention,
  type InspirationUrl,
  type PlatformHint,
  type PromptStyleAnalysis,
  type CompetitorAnalysis,
  type DomainResearch,
  type TechRecommendation,
  type StyleConstraints,
  type StyleResearchOutput,
  // Helper functions
  extractStyleHintsFromPrompt,
  createEmptyStyleConstraints,
  createEmptyPromptAnalysis,
  MOOD_STYLE_MAPPING,
} from './schemas/analyst-style-output.js';

// Project Analyzer schemas
export {
  DetectedLanguageSchema,
  FrameworkTypeSchema,
  DetectedFrameworkSchema,
  ImportanceSchema,
  DirectoryAnalysisSchema,
  PatternCategorySchema,
  DetectedPatternSchema,
  IssueTypeSchema,
  CodeQualityIssueSchema,
  CodeQualitySchema,
  ComplianceIndicatorsSchema,
  EntryPointTypeSchema,
  EntryPointSchema,
  OutdatedSeveritySchema,
  OutdatedDependencySchema,
  VulnerabilitySeveritySchema,
  DependencyVulnerabilitySchema,
  DependencyAnalysisSchema,
  RecommendationCategorySchema,
  RecommendationPrioritySchema,
  AnalysisRecommendationSchema,
  ProjectTypeSchema,
  TechStackSummarySchema,
  ProjectStructureSchema,
  ArchitectureSummarySchema,
  GeneratedContextSchema,
  ProjectAnalyzerRoutingHintsSchema,
  ProjectAnalyzerOutputSchema,
  createDetectedLanguage,
  createDetectedFramework,
  createEmptyCodeQuality,
  createEmptyComplianceIndicators,
  createRecommendation as createAnalysisRecommendation,
  calculatePrimaryLanguage,
  countIssuesByType,
  getHighPriorityRecommendations,
  isValidPath,
  type DetectedLanguage,
  type FrameworkType,
  type DetectedFramework,
  type Importance,
  type DirectoryAnalysis as ProjectDirectoryAnalysis,
  type PatternCategory,
  type DetectedPattern,
  type IssueType,
  type CodeQualityIssue,
  type CodeQuality,
  type ComplianceIndicators,
  type EntryPointType,
  type EntryPoint,
  type OutdatedSeverity,
  type OutdatedDependency,
  type VulnerabilitySeverity,
  type DependencyVulnerability,
  type DependencyAnalysis,
  type RecommendationCategory,
  type RecommendationPriority,
  type AnalysisRecommendation,
  type ProjectType,
  type TechStackSummary,
  type ProjectStructure,
  type ArchitectureSummary,
  type GeneratedContext,
  type ProjectAnalyzerRoutingHints,
  type ProjectAnalyzerOutput,
} from './schemas/project-analyzer-output.js';

// Analysis utilities
export {
  LANGUAGE_EXTENSIONS,
  FRAMEWORK_RULES,
  DIRECTORY_PURPOSE_MAP,
  DIRECTORY_IMPORTANCE,
  analyzeLanguages,
  detectFrameworks,
  analyzeDirectories,
  analyzeCodeQuality,
  detectEntryPoints,
  analyzeDependencies,
  inferProjectType,
  detectPatterns,
  type FrameworkRule,
  type FileInfo,
  type DirectoryInfo,
  type PackageDependencies,
  type PreAnalyzedData,
} from './analysis/index.js';

// Project Analyzer agent
export { ProjectAnalyzerAgent } from './agents/project-analyzer.js';

// Compliance schemas
export {
  ComplianceFrameworkSchema,
  ViolationSeveritySchema,
  ViolationLocationSchema,
  ViolationSchema,
  CheckResultSchema,
  DataSensitivitySchema,
  DataTypeClassificationSchema,
  DataFlowSchema,
  RetentionPolicySchema,
  DataHandlingSchema,
  AuthenticationAssessmentSchema,
  AuthorizationAssessmentSchema,
  EncryptionAssessmentSchema,
  SecretManagementAssessmentSchema,
  SecurityAssessmentSchema,
  EffortLevelSchema,
  ComplianceRecommendationSchema,
  ComplianceScoreSchema,
  ScanTypeSchema,
  ComplianceStatusSchema,
  ComplianceSummarySchema,
  ComplianceRoutingHintsSchema,
  ComplianceOutputSchema,
  createViolation,
  createCheckResult,
  createComplianceScore,
  createEmptySecurityAssessment,
  createEmptyDataHandling,
  calculateComplianceSummary,
  countViolationsBySeverity,
  countViolationsByFramework,
  getBlockingViolations,
  filterViolationsByFramework,
  isFullyCompliant,
  type ComplianceFramework,
  type ViolationSeverity,
  type ViolationLocation,
  type Violation,
  type CheckResult as ComplianceCheckResult,
  type DataSensitivity,
  type DataTypeClassification,
  type DataFlow,
  type RetentionPolicy,
  type DataHandling,
  type AuthenticationAssessment,
  type AuthorizationAssessment,
  type EncryptionAssessment,
  type SecretManagementAssessment,
  type SecurityAssessment,
  type EffortLevel,
  type ComplianceRecommendation,
  type ComplianceScore,
  type ScanType,
  type ComplianceStatus,
  type ComplianceSummary,
  type ComplianceRoutingHints,
  type ComplianceOutput,
} from './schemas/compliance-output.js';

// Compliance utilities
export {
  SECRET_PATTERNS,
  INSECURE_URL_PATTERN,
  CARD_DATA_PATTERNS,
  checkHardcodedSecrets,
  checkAuditLogging,
  checkInputValidation,
  checkHttpsEnforcement,
  checkSqlInjection,
  checkConsentMechanism,
  checkDeletionCapability,
  checkAccessControl,
  checkChangeManagement,
  checkCardDataStorage,
  PLATFORM_RULES,
  GDPR_RULES,
  SOC2_RULES,
  PCIDSS_RULES,
  RULES_BY_FRAMEWORK,
  getRulesForFrameworks,
  evaluateCompliance,
  type FileContent,
  type ComplianceConfig,
  type RuleContext,
  type RuleCheckResult,
  type ComplianceRule,
} from './compliance/index.js';

// Compliance agent
export { ComplianceAgent } from './agents/compliance.js';

// UI Designer schemas
export {
  UIComponentTypeSchema,
  AccessibilitySchema,
  BreakpointSchema,
  BREAKPOINT_VALUES,
  StyleSchema,
  ResponsiveStylesSchema,
  ComponentVariantSchema,
  UIComponentSchema,
  LayoutTypeSchema,
  LayoutRegionSchema,
  PageLayoutSchema,
  ThemeSchema,
  PageMetaSchema,
  MockupPageSchema,
  ColorPaletteSchema,
  TypographySchema,
  SpacingSchema,
  BorderRadiusSchema,
  ShadowsSchema,
  UIDesignerRoutingHintsSchema,
  UIDesignerOutputSchema,
  createDefaultColorPalette,
  createDefaultTypography,
  createDefaultSpacing,
  createDefaultBorderRadius,
  createDefaultShadows,
  createUIComponent,
  createMockupPage,
  countComponents,
  flattenComponents,
  findComponentById,
  getComponentsByType,
  validateUniqueIds,
  hasAccessibility,
  countAccessibleComponents,
  type UIComponentType,
  type Accessibility,
  type Breakpoint,
  type Style,
  type ResponsiveStyles,
  type ComponentVariant,
  type UIComponent,
  type LayoutType,
  type LayoutRegion,
  type PageLayout,
  type Theme,
  type PageMeta,
  type MockupPage,
  type ColorPalette,
  type Typography,
  type Spacing,
  type BorderRadius,
  type Shadows,
  type UIDesignerRoutingHints,
  type UIDesignerOutput,
} from './schemas/ui-designer-output.js';

// Competitive design schemas
export {
  DesignStyleSchema,
  DesignFocusSchema,
  ColorSchemeTypeSchema,
  DesignVariantSchema,
  DesignTradeoffSchema,
  CompetitionMetadataSchema,
  CompetitiveDesignOutputSchema,
  DesignSubmissionSchema,
  CompetitionWinnerSchema,
  DesignCompetitionResultSchema,
  CompetitionOptionsSchema,
  DESIGN_STYLES,
  DESIGN_FOCUSES,
  COLOR_SCHEMES,
  generateVariantAssignments,
  getStyleGuidance,
  getFocusGuidance,
  getColorSchemeGuidance,
  buildVariantInstruction,
  getSuccessfulSubmissions,
  getWinningDesign,
  calculateSuccessRate,
  sortSubmissionsByScore,
  getDesignByVariant,
  type DesignStyle,
  type DesignFocus,
  type ColorSchemeType,
  type DesignVariant,
  type DesignTradeoff,
  type CompetitionMetadata,
  type CompetitiveDesignOutput,
  type DesignSubmission,
  type CompetitionWinner,
  type DesignCompetitionResult,
  type CompetitionOptions,
} from './schemas/competitive-design.js';

// Design utilities
export {
  escapeHtml,
  escapeAttribute,
  camelToKebab,
  styleObjectToString,
  renderAccessibility,
  getHtmlTag,
  renderAttributes,
  renderComponent,
  generateColorVariables,
  generateTypographyVariables,
  generateSpacingVariables,
  generateBorderRadiusVariables,
  generateShadowVariables,
  generateCSSVariables,
  generateBaseCSS,
  generatePageHTML,
  generateComponentDoc,
  slugify,
} from './design/index.js';

// UI Designer agent
export { UIDesignerAgent } from './agents/ui-designer.js';

// Skills framework
export {
  // Schemas
  SkillCategorySchema,
  SkillPrioritySchema,
  SkillExampleSchema,
  SkillConditionsSchema,
  SkillDefinitionSchema,
  SkillPackSchema,
  SkillSourceSchema,
  LoadedSkillSchema,
  SkillSelectionCriteriaSchema,
  // Types
  type SkillCategory,
  type SkillPriority,
  type SkillExample,
  type SkillConditions,
  type SkillDefinition,
  type SkillPack,
  type SkillSource,
  type LoadedSkill,
  type SkillSelectionCriteria,
  type ExcludedSkill,
  type SelectedSkills,
  type SkillInjection,
  // Constants
  SKILL_CATEGORIES,
  PRIORITY_WEIGHTS,
  // Helper functions
  createSkillDefinition,
  createSkillPack,
  toLoadedSkill,
  calculateTotalTokens,
  filterByCategory as filterSkillsByCategory,
  filterByTag as filterSkillsByTag,
  sortByPriority as sortSkillsByPriority,
  getUniqueTags,
  validateSkillPack as validateSkillPackSchema,
  safeParseSkillPack,
  // Registry
  SkillRegistry,
  getSkillRegistry,
  resetSkillRegistry,
  type RegistryStats as SkillRegistryStats,
  // Loader
  loadSkillPack,
  loadSkillPacks,
  loadSkill,
  loadBuiltInSkills,
  getBuiltInSkillPack,
  validatePack,
  validateSkillDefinition,
  mergeSkillPacks,
  filterSkillPack,
  getPackSummary,
  BUILT_IN_SKILLS,
  type LoadResult,
  type LoadError,
  type LoadOptions,
  type ValidationResult as SkillValidationResult,
  type ValidationError as SkillValidationError,
  type ValidationWarning,
  // Injector
  injectSkills,
  injectSkillsMinimal,
  injectSkillsCompact,
  injectSkillsXml,
  formatSkillList,
  getSkillsSummary,
  type InjectionFormat,
  type InjectionOptions,
} from './skills/index.js';

// Structured output utilities
export {
  STRUCTURED_OUTPUT_INSTRUCTION,
  buildStructuredOutputPrompt,
  extractJSON,
  parseWithSchema,
  generateRetryPrompt,
  SCHEMA_DESCRIPTIONS,
  wrapSystemPrompt,
  type ParseResult,
} from './utils/index.js';

// Self-Review framework
export {
  // Version
  SELF_REVIEW_VERSION,
  // Constants
  MAX_DESCRIPTION_LENGTH as REVIEW_MAX_DESCRIPTION_LENGTH,
  MAX_REASONING_LENGTH,
  MAX_GAPS,
  MAX_REQUIREMENTS,
  // Gap schemas
  GapSeveritySchema,
  type GapSeverity,
  GapCategorySchema,
  type GapCategory,
  EffortEstimateSchema,
  type EffortEstimate,
  GapSchema,
  type Gap,
  // Requirement coverage
  RequirementSourceSchema,
  type RequirementSource,
  RequirementCoverageSchema,
  type RequirementCoverage,
  // Review decision
  ReviewDecisionSchema,
  type ReviewDecision,
  // Review result
  SelfReviewResultSchema,
  type SelfReviewResult,
  // Configuration
  SelfReviewConfigSchema,
  type SelfReviewConfig,
  DEFAULT_SELF_REVIEW_CONFIG,
  // Validation helpers
  createGap,
  createRequirementCoverage,
  validateSelfReviewResult,
  validateSelfReviewConfig,
  // Self-review loop
  type SelfReviewExecuteResult,
  SelfReviewLoop,
  createSelfReviewLoop,
  // Gap addresser
  type ImprovementData,
  buildGapAddressingPrompt,
  mergeImprovements,
  getFixableGaps,
  getGapsBySeverity,
  getGapsByCategory,
  prioritizeGaps,
  estimateTotalEffort,
  // Criteria
  type CriterionResult,
  type ReviewCriterion,
  type ReviewContext,
  type AgentReviewCriteria,
  BaseAgentReviewCriteria,
  criterionPassed,
  criterionFailed,
  criterionPartial,
  UIDesignerReviewCriteria,
  createUIDesignerCriteria,
  ProjectManagerReviewCriteria,
  createProjectManagerCriteria,
  // Learning integration
  type LessonInput,
  type GapPattern,
  type ReviewMetrics,
  createLessonFromReview,
  analyzeGapPatterns,
  analyzeSuccessfulFixes,
  findCommonMissedRequirements,
  calculateReviewMetrics,
} from './review/index.js';
