/**
 * Design Workflow Types
 *
 * Types and schemas for the design-first workflow system.
 *
 * Security features:
 * - Zod validation for all schemas
 * - Max length constraints on strings
 * - Bounded arrays to prevent payload abuse
 */

import { z } from 'zod';

// ============================================================================
// Constants
// ============================================================================

export const MAX_NAME_LENGTH = 200;
export const MAX_DESCRIPTION_LENGTH = 5000;
export const MAX_HTML_LENGTH = 500000; // 500KB
export const MAX_CSS_LENGTH = 200000; // 200KB
export const MAX_SCREENS = 100;
export const MAX_COMPONENTS = 200;
export const MAX_COLORS = 20;

// ============================================================================
// Design Mood
// ============================================================================

/**
 * Design mood/style variants
 */
export const DesignMoodSchema = z.enum([
  'minimalist',
  'bold',
  'elegant',
  'playful',
  'corporate',
  'modern',
  'classic',
  'futuristic',
]);

export type DesignMood = z.infer<typeof DesignMoodSchema>;

// ============================================================================
// Design Colors
// ============================================================================

/**
 * Color value (hex, rgb, hsl)
 */
export const ColorValueSchema = z.string().regex(
  /^(#[0-9A-Fa-f]{3,8}|rgb\(|rgba\(|hsl\(|hsla\(|var\(--)/,
  'Invalid color format'
);

/**
 * Design color palette
 */
export const DesignColorsSchema = z.object({
  primary: ColorValueSchema,
  secondary: ColorValueSchema,
  accent: ColorValueSchema,
  background: ColorValueSchema,
  surface: ColorValueSchema,
  text: ColorValueSchema,
  textSecondary: ColorValueSchema.optional(),
  error: ColorValueSchema.optional(),
  success: ColorValueSchema.optional(),
  warning: ColorValueSchema.optional(),
});

export type DesignColors = z.infer<typeof DesignColorsSchema>;

// ============================================================================
// Design Typography
// ============================================================================

/**
 * Typography settings
 */
export const DesignTypographySchema = z.object({
  headingFont: z.string().max(200),
  bodyFont: z.string().max(200),
  monoFont: z.string().max(200).optional(),
  baseFontSize: z.string().max(20).optional(),
  lineHeight: z.string().max(20).optional(),
  fontWeightNormal: z.string().max(10).optional(),
  fontWeightBold: z.string().max(10).optional(),
});

export type DesignTypography = z.infer<typeof DesignTypographySchema>;

// ============================================================================
// Design Spacing
// ============================================================================

/**
 * Spacing scale
 */
export const DesignSpacingSchema = z.object({
  unit: z.string().max(20).optional(),
  xs: z.string().max(20).optional(),
  sm: z.string().max(20).optional(),
  md: z.string().max(20).optional(),
  lg: z.string().max(20).optional(),
  xl: z.string().max(20).optional(),
});

export type DesignSpacing = z.infer<typeof DesignSpacingSchema>;

// ============================================================================
// Design Tokens
// ============================================================================

/**
 * Extracted design tokens from HTML
 */
export const ExtractedTokensSchema = z.object({
  colors: DesignColorsSchema,
  typography: DesignTypographySchema,
  spacing: DesignSpacingSchema.optional(),
  borderRadius: z.string().max(50).optional(),
  shadows: z.array(z.string().max(200)).max(10).optional(),
});

export type ExtractedTokens = z.infer<typeof ExtractedTokensSchema>;

// ============================================================================
// Design Component
// ============================================================================

/**
 * Extracted component pattern
 */
export const DesignComponentSchema = z.object({
  name: z.string().max(MAX_NAME_LENGTH),
  type: z.enum([
    'button',
    'card',
    'form',
    'input',
    'modal',
    'navigation',
    'header',
    'footer',
    'list',
    'table',
    'alert',
    'badge',
    'avatar',
    'dropdown',
    'tabs',
    'other',
  ]),
  html: z.string().max(MAX_HTML_LENGTH),
  css: z.string().max(MAX_CSS_LENGTH).optional(),
  classes: z.array(z.string().max(100)).max(50).optional(),
  description: z.string().max(MAX_DESCRIPTION_LENGTH).optional(),
});

export type DesignComponent = z.infer<typeof DesignComponentSchema>;

// ============================================================================
// Design Option
// ============================================================================

/**
 * A single design option generated by UI Designer
 */
export const DesignOptionSchema = z.object({
  id: z.string().max(100),
  name: z.string().max(MAX_NAME_LENGTH),
  mood: DesignMoodSchema,
  description: z.string().max(MAX_DESCRIPTION_LENGTH),
  html: z.string().max(MAX_HTML_LENGTH),
  css: z.string().max(MAX_CSS_LENGTH).optional(),
  tokens: ExtractedTokensSchema.optional(),
  colorPalette: z.array(ColorValueSchema).max(MAX_COLORS).optional(),
  components: z.array(DesignComponentSchema).max(MAX_COMPONENTS).optional(),
  createdAt: z.string().datetime().optional(),
});

export type DesignOption = z.infer<typeof DesignOptionSchema>;

// ============================================================================
// Screen Definition
// ============================================================================

/**
 * Screen category for organizing mockups
 */
export const ScreenCategorySchema = z.enum([
  'public',
  'auth',
  'dashboard',
  'admin',
  'settings',
  'profile',
  'other',
]);

export type ScreenCategory = z.infer<typeof ScreenCategorySchema>;

/**
 * A screen identified by PM agent
 */
export const ScreenDefinitionSchema = z.object({
  id: z.string().max(100),
  name: z.string().max(MAX_NAME_LENGTH),
  description: z.string().max(MAX_DESCRIPTION_LENGTH),
  category: ScreenCategorySchema,
  elements: z.array(z.string().max(200)).max(100).optional(),
  userStory: z.string().max(2000).optional(),
});

export type ScreenDefinition = z.infer<typeof ScreenDefinitionSchema>;

// ============================================================================
// Screen Mockup
// ============================================================================

/**
 * Generated screen mockup
 */
export const ScreenMockupSchema = z.object({
  screenId: z.string().max(100),
  name: z.string().max(MAX_NAME_LENGTH),
  html: z.string().max(MAX_HTML_LENGTH),
  css: z.string().max(MAX_CSS_LENGTH).optional(),
  path: z.string().max(500).optional(),
  generatedAt: z.string().datetime().optional(),
});

export type ScreenMockup = z.infer<typeof ScreenMockupSchema>;

// ============================================================================
// Kitchen Sink
// ============================================================================

/**
 * Kitchen sink / component library output
 */
export const KitchenSinkSchema = z.object({
  html: z.string().max(MAX_HTML_LENGTH),
  css: z.string().max(MAX_CSS_LENGTH),
  components: z.array(DesignComponentSchema).max(MAX_COMPONENTS),
  classes: z.array(z.string().max(100)).max(500),
  generatedAt: z.string().datetime(),
});

export type KitchenSink = z.infer<typeof KitchenSinkSchema>;

// ============================================================================
// Design Spec
// ============================================================================

/**
 * Design specification for consistent styling
 */
export const DesignSpecSchema = z.object({
  designName: z.string().max(MAX_NAME_LENGTH),
  mood: DesignMoodSchema,
  cssVariables: z.string().max(MAX_CSS_LENGTH),
  colorInstructions: z.string().max(5000),
  typographyInstructions: z.string().max(5000),
  spacingInstructions: z.string().max(5000).optional(),
  componentSnippets: z.record(z.string().max(MAX_HTML_LENGTH)).optional(),
});

export type DesignSpec = z.infer<typeof DesignSpecSchema>;

// ============================================================================
// Workflow Configuration
// ============================================================================

/**
 * Design workflow configuration
 */
export const WorkflowConfigSchema = z.object({
  // Output settings
  outputDir: z.string().max(500).default('.aigentflow/designs'),
  generateGallery: z.boolean().default(true),

  // Design options
  designCount: z.number().int().min(1).max(5).default(3),
  defaultMoods: z.array(DesignMoodSchema).max(5).default(['minimalist', 'bold', 'elegant']),

  // Auto-selection
  autoSelect: z.number().int().min(0).max(5).default(0), // 0 = prompt user
  skipApproval: z.boolean().default(false),

  // Timeouts
  designTimeoutMs: z.number().int().min(30000).max(600000).default(300000),
  mockupTimeoutMs: z.number().int().min(30000).max(300000).default(120000),

  // Concurrency
  maxConcurrentDesigners: z.number().int().min(1).max(15).default(3),
  maxConcurrentMockups: z.number().int().min(1).max(10).default(5),
});

export type WorkflowConfig = z.infer<typeof WorkflowConfigSchema>;

// ============================================================================
// Workflow Result
// ============================================================================

/**
 * Workflow execution result
 */
export const WorkflowResultSchema = z.object({
  success: z.boolean(),
  selectedDesign: DesignOptionSchema.optional(),
  designOptions: z.array(DesignOptionSchema).max(5),
  screens: z.array(ScreenDefinitionSchema).max(MAX_SCREENS),
  mockups: z.array(ScreenMockupSchema).max(MAX_SCREENS),
  kitchenSink: KitchenSinkSchema.optional(),
  outputDir: z.string().max(500),
  galleryPath: z.string().max(500).optional(),
  errors: z.array(z.string().max(5000)).max(100),
  duration: z.number().int().min(0),
});

export type WorkflowResult = z.infer<typeof WorkflowResultSchema>;

// ============================================================================
// Validation Helpers
// ============================================================================

/**
 * Validate a design option
 */
export function validateDesignOption(
  option: unknown
): { success: true; data: DesignOption } | { success: false; error: z.ZodError } {
  const result = DesignOptionSchema.safeParse(option);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return { success: false, error: result.error };
}

/**
 * Validate workflow config
 */
export function validateWorkflowConfig(
  config: unknown
): { success: true; data: WorkflowConfig } | { success: false; error: z.ZodError } {
  const result = WorkflowConfigSchema.safeParse(config);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return { success: false, error: result.error };
}

/**
 * Create a default workflow config
 */
export function createDefaultConfig(overrides?: Partial<WorkflowConfig>): WorkflowConfig {
  return WorkflowConfigSchema.parse(overrides ?? {});
}
